### ISSUE TITLE
Make LimitNOFILE in systemd service configurable

### ISSUE THREAD

**Issue by michaelkebe** [patrickjahns/ansible-role-promtail#129]
It should be possible to change the maximum of allown open files for the systemd promtail service.

It can be achieved by add the `LimitNOFILE` parameter to the `[Service]` section.

The name of the variable could be something like `promtail_limit_open_files`.

Example:
```
[Service]
Restart=always
RestartSec=5
TimeoutSec=5
LimitNOFILE={{ promtail_limit_open_files }}
User={{ promtail_system_user }}
Group={{ promtail_system_group }}
ExecStart=/usr/local/bin/promtail -config.file={{ promtail_config_file }} -log.level={{ promtail_log_level }}
```

**Comment by patrickjahns** [comment]
I gave your suggestion a thought - I suppose there are going to be more options in the future for systemd that would make sense to expose to users. As these options are arbitrary and very specific to the needs of individual people, exposing them via individual parameters is a lot of overhead.
Instead I would propose to introduce the variable `promtail_systemd_options` where one can pass arbitrary options which are then rendered into the unit file. That would address your proposal - wdyt?

**Comment by michaelkebe** [comment]
Maybe this is not needed because of systemd drop in overrides.

See
https://unix.stackexchange.com/questions/398540/how-to-override-systemd-unit-file-settings

What do you think?

**Comment by patrickjahns** [comment]
Thanks for sharing, I was not aware of the overrides, but it makes sense to use them. Did you try it in your environment?

**Comment by michaelkebe** [comment]
Yes, we are using it without any issues.
