### ISSUE TITLE
1.19.1 no longer works: user promtail is currently used by process 546

### ISSUE THREAD

**Issue by shinebayar-g** [patrickjahns/ansible-role-promtail#140]
I updated role from `1.18.0` to `1.19.1`. Now role no longer works for me.

```
TASK [patrickjahns.promtail : Ensure unzip package is available] ************************************************************************************************************************************************
ok: [test]

TASK [patrickjahns.promtail : Create promtail group] ************************************************************************************************************************************************************
ok: [test]

TASK [patrickjahns.promtail : Create the promtail user] *********************************************************************************************************************************************************
fatal: [test]: FAILED! => changed=false
  msg: |-
    usermod: user promtail is currently used by process 546
  name: promtail
  rc: 8

PLAY RECAP ******************************************************************************************************************************************************************************************************
test                       : ok=27   changed=0    unreachable=0    failed=1    skipped=17   rescued=0    ignored=0
```

Ubuntu 22.04.1 LTS. Looks like it's caused by https://github.com/patrickjahns/ansible-role-promtail/pull/138 reverting for now.

**Comment by hafu** [comment]
I'll will check on Monday. I assume I's because the users home is tried to changed by the Ansible user module with a process running as the user and this fails.

It it is the case, I could add a check if the users current home will be changed and stop the promtail process before running this task. But this would add some complexity to the role only to change the users home.

**Comment by patrickjahns** [comment]
@shinebayar-g 
Thanks for reporting - I was not expecting that change to create issues. I've created a test case for catching regressions in the future #141 

@hafu 
I'd gladly appreciate if you provide a fix for the regression - thank you :-)

**Comment by hafu** [comment]
I could reproduce the issue. And came up with two options:

1. As mentioned by @shinebayar-g https://github.com/patrickjahns/ansible-role-promtail/pull/138#issuecomment-1328119073 omitting the `home`. This would not touch the home of the user on existing installations ('/') and on new installations it would be the default `/home/promtail` or `/home/{{ promtail_system_user }}`.
2. Check for the user and if exists make sure there is no process running by stopping promtail when the home changes. I've added some additional tasks: https://github.com/patrickjahns/ansible-role-promtail/commit/a481b4d101d25ded34921668cbcc196d58be8061

What do you think?

**Comment by patrickjahns** [comment]
Thanks for reaching out - personally I believe number 1) is the less intrusive one and with the less maintenance overhead in the long run.
