### ISSUE TITLE
Add variable (list) for additional command line arguments/flags passed to promtail

### ISSUE THREAD

**Issue by life5ign** [patrickjahns/ansible-role-promtail#167]
e.g., I'd like to use "-print-config-stderr", plus a few others, but can't with this role; this variable can be a list, and if it's defined, they can be looped over when templating the systemd unit file.  

The variable could be "promtail_additional_arguments" or "promtail_additional_runtime_flags" and default to `[]`

I consider this a very important feature, so the user isn't limited by what is defined in the role.  Thanks, great role!

**Comment by patrickjahns** [comment]
This sounds like a very useful feature - I'd be happy to accept a pull request for this.

I would not be using this feature myself - so extending one of the test-cases would probably be good, so we can catch if there are any regressions with that feature.
