### ISSUE TITLE
Support arbitrary options in the configuration file

### ISSUE THREAD

**Issue by pavlozt** [patrickjahns/ansible-role-promtail#203]
Sometimes (and in the future) it becomes necessary to add options that the role creator did not provide
For example, I need override backoff_config.  But I don't find any global level variable.
Other people have also mentioned limits_config, etc.

**Comment by pavlozt** [comment]
Ok. This is not so actual options. backoff_config is part of promtail_config_clients.

**Comment by patrickjahns** [comment]
I understand your request - how would you propose that this could be best addressed and resolved? 
Is it possible to address this without introducing a breaking change to the current behaviour ?

**Comment by pavlozt** [comment]
@patrickjahns I suggest leaving everything as is.   backoff_config
There are not many options in this program and I have no burning practical need
