### ISSUE TITLE
Why is the promtail_config_positions empty by default?

### ISSUE THREAD

**Issue by funkyfuture** [patrickjahns/ansible-role-promtail#37]
ciao, please note that i'm currently in the process to get acquainted with loki and promtail. i was just wondering why the default for `promtail_config_positions` is an empty mapping. the application's default is `/var/log/positions.yml` which it can't write to when deployed with this role.

**Comment by patrickjahns** [comment]
It was kept empty to use the default from loki and allow to override it when the environment requires this. 

When looking at upstream, it will default to `/var/log/positions.yml` - https://github.com/grafana/loki/blob/master/pkg/promtail/positions/positions.go#L33 

Possible ways forward that I see:
- define the variable per default and ensure that file is writeable by the promtail user/group
- ensure that promtail is added to the `syslog` group per default, then the any file in `/var/log/*` would be writeable by promtail 

Open to further suggestions and happy to accept a PR :-)

**Comment by funkyfuture** [comment]
i hope to come back w/ a pr when i'm through w/ my whole setup. just saying that `/var/log/…` seems wrong, `/tmp/…` is okay and working, but `/var/promtail/positions.yml` makes the most correct impression to me.
