### ISSUE TITLE
Add upstream sync script

### ISSUE THREAD

**Issue by patrickjahns** [patrickjahns/ansible-role-promtail#4]
In order to keep up-to-date with upstream changes, lets add a sync script / bot that will check for newer upstream releases and then create a pull request with the according version bump

**Comment by triwats** [comment]
👍

**Comment by MindTooth** [comment]
I highly recommend [Renovate](https://github.com/renovatebot/renovate/).  I'll gladly help out if need be. 😄

**Comment by patrickjahns** [comment]
@MindTooth  - sorry for the very delayed reply - didn't catch your message earlier. 
Thanks for the hint with Renovate - I am curious to set this up. Feel free to submit a pull request if I don't get around to it anytime soon
