### ISSUE TITLE
Entry_parser setting is no longer needed in playbook examples

### ISSUE THREAD

**Issue by tideline3d** [patrickjahns/ansible-role-promtail#47]
Im trying to set up a simple example of deploying Promtail and running into a weird problem where the generated YAML scrape configuration isn't written out like my playbook describes.   I cant think of why this would happen, hoping for an idea or two on how to get around this.   

Here's my playbook:
![image](https://user-images.githubusercontent.com/12903320/103326411-38f53380-4a1e-11eb-9638-97820a48b863.png)

On my target machine, this is the resulting /etc/promtail/promtail.yml
![image](https://user-images.githubusercontent.com/12903320/103326395-1cf19200-4a1e-11eb-9286-8d49bcc087fe.png)

Notice how Jobname and Entry Parser are reversed?  Promtail fails to start  with this error after running the playbook.   Labels and targets are generated backwards as well.  
![image](https://user-images.githubusercontent.com/12903320/103326435-562a0200-4a1e-11eb-9cd0-7c83f573de1a.png)

**Comment by patrickjahns** [comment]
You error seems to be related to an invalid `scrap_config` block - I faintly recall that `entry_parser`  was removed from the promtail configuration. Please check if the config you are pushing is valid

> Notice how Jobname and Entry Parser are reversed? 

The order of keys do not matter in yaml - so this is unrelated to the error you are encountering

**Comment by patrickjahns** [comment]
Quick search for `entry_parser` yielded the following remark - https://github.com/grafana/loki/blob/f3da16797742bc7135ebd5ab1e27187a8d9ddd2f/docs/sources/upgrading/_index.md#promtail-config-removed 

So I suggest to drop it from your configuration
Please drop it from your configuration

**Comment by tideline3d** [comment]
Thanks @patrickjahns, don't know how I missed that in my searching.  It was a late night!   I submitted a PR to update your examples to drop that setting as well.

**Comment by patrickjahns** [comment]
Thanks for updating the README - will close the issue here if thats alright :-)
