### ISSUE TITLE
Version 1.10.0 not available on Galaxy

### ISSUE THREAD

**Issue by triwats** [patrickjahns/ansible-role-promtail#53]
Version 1.10.0 did not complete it's CI/CD pipeline and therefore it has not been successfully pushed to Galaxy. The commit reference seems to need [RELEASE], but that is there.

From our CI: 
```[WARNING]: - patrickjahns.promtail was NOT installed successfully: - the
specified version (1.10.0) of patrickjahns.promtail was not found in the list
of available versions ([{'id': 115455, 'url': '', 'related': {},
```

The Ansible Galaxy release still shows [only the 1.9.1 version](https://galaxy.ansible.com/patrickjahns/promtail/) - which is what we were using previously. 

**Update**:

From looking at the Github actions that are carried out to manage releases there's a bit of regex foo:

```Run VERSION=$(echo "${COMMIT_MSG}" | grep -Po '\d.\d.\d')```

And the current `${COMMIT_MSG}`:

```
  env:
    COMMIT_MSG: Merge pull request #52 from patrickjahns/release/next
  
  [RELEASE] 1.10.0
```

Since we're now on double digits, we are unable to match via this regex. The alternative would be: `grep -Po '\d.\d\d.\d')`. 

To fix this, an grep OR in the regex could work? This would mean it would read: 

```
Run VERSION=$(echo "${COMMIT_MSG}" | grep -Po '(\d.\d.\d)|(\d.\d\d.\d)'
```

Example is here: https://regex101.com/r/WouePL/1

Happy to try to raise a PR for this if you think this is suitable.

**Comment by patrickjahns** [comment]
@triwats 

Highly appreciate your report 👍  - and the detailed information where things went wrong - thank you very much!

Simplified the regex to `\d+.\d+.\d+` and just pushed it via #54.

**Comment by patrickjahns** [comment]
Should now be available on Galaxy

**Comment by triwats** [comment]
No worries, that works too! Thanks a lot for the module, I can confirm that this now works. Have a good easter and thanks for quickly addressing it! Closing.

```
- downloading role 'promtail', owned by patrickjahns
- downloading role from https://github.com/patrickjahns/ansible-role-promtail/archive/1.10.0.tar.gz
- extracting patrickjahns.promtail to /root/.ansible/roles/patrickjahns.promtail
- patrickjahns.promtail (1.10.0) was installed successfully
```
