### ISSUE TITLE
Remove update_cache or make it optional

### ISSUE THREAD

**Issue by mweinelt** [patrickjahns/ansible-role-promtail#63]
In the step that ensure unzip is installed to the managed hosts you are setting `update_cache: yes`.

https://github.com/patrickjahns/ansible-role-promtail/blob/dd3c702e45ce06be4759302043b24c07dcf79f09/tasks/install.yml#L2-L6

Would it be a reasonable ask to let administrators handle `update_cache` themselves, so `apt-get update` is only executed once per run, instead of possibly multiple times, due to this role forcing it?

**Comment by patrickjahns** [comment]
If we are not updating the cache per default, I fear that the installation might fail for people who are not aware, that they need to have updated the cache themselves first. In my mind this leads to a bad default experience with ansible roles.

I'd be open for a suggestion how to best handle this. Do you know of any convention (i.e. a specific variable name) that we could use to conditionally enable/disable the behaviour ?

**Comment by mweinelt** [comment]
> If we are not updating the cache per default, I fear that the installation might fail for people who are not aware, that they need to have updated the cache themselves first. In my mind this leads to a bad default experience with ansible roles.

I see.

> I'd be open for a suggestion how to best handle this. Do you know of any convention (i.e. a specific variable name) that we could use to conditionally enable/disable the behaviour ?

I'm unaware of any convention, sorry.

**Comment by patrickjahns** [comment]
> I'm unaware of any convention, sorry. Making it a variable, that is default true, so we could opt-out of the behaviour would be great.

Sounds like a good compromise to me - happy to get a PR and would gladly build a new release 👍
